[pytest]
addopts =
    -n 4
    -s -v
    --alluredir=allure-results
    --reruns 3
    --reruns-delay 1

markers =
    characters: tests of characters endpoints
    negative
    positive
    random: tests of random endpoints
    regression
    smoke
    tokens: tests of tokens endpoints
    users: tests of users endpoints